[project]
name = "datalab-beholder"
dynamic = ["version"]
description = "Filesystem watcher daemon for datalab instances"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10, <3.13"
dependencies = [
    "click ~= 8.3",
    "datalab-api ~= 0.5",
    "pydantic ~= 2.12",
    "pyyaml ~= 6.0",
]

[project.scripts]
datalab-beholder = "datalab_beholder.cli:main"

[build-system]
requires = ["setuptools >= 77.0.3", "setuptools_scm>=8.1,<10.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.1.0"
version_scheme = "post-release"

[dependency-groups]
dev = [
    "pyinstaller ~= 6.19",
    "pytest ~= 9.0",
    "pre-commit ~= 4.5"
]
